# Generated by Django 5.2.8 on 2025-11-29 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorekCesidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Börek Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (TL)')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='borekler/', verbose_name='Ürün Resmi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Börek Çeşidi',
                'verbose_name_plural': 'Börek Çeşitleri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
                ('okundu', models.BooleanField(default=False, verbose_name='Okundu')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('adres', models.TextField(verbose_name='Teslimat Adresi')),
                ('adet', models.PositiveIntegerField(default=1, verbose_name='Adet')),
                ('not_mesaj', models.TextField(blank=True, null=True, verbose_name='Sipariş Notu')),
                ('durum', models.CharField(choices=[('yeni', 'Yeni Sipariş'), ('hazirlaniyor', 'Hazırlanıyor'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal Edildi')], default='yeni', max_length=20, verbose_name='Sipariş Durumu')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat')),
                ('siparis_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sipariş Tarihi')),
                ('borek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ana_sayfa.borekcesidi', verbose_name='Börek Çeşidi')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-siparis_tarihi'],
            },
        ),
    ]
