# Generated by Django 5.2.8 on 2025-11-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='ad_soyad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ad Soyad'),
        ),
    ]
