# Generated by Django 5.2.8 on 2025-11-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0002_alter_siparis_ad_soyad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('yeni', 'Yeni Sipariş'), ('hazirlaniyor', 'Hazırlanıyor'), ('yolda', 'Yolda'), ('teslim_edildi', 'Teslim Edildi'), ('iptal', 'İptal Edildi')], default='yeni', max_length=20, verbose_name='Sipariş Durumu'),
        ),
    ]
